name=M5Unit-RF433
version=0.0.1
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT RF433 using M5UnitUnified
paragraph=Supports UnitRF433T (SYN115 transmitter) and UnitRF433R (SYN531R receiver) for 433.92MHz ASK wireless communication.
category=Device Control
url=https://github.com/m5stack/M5Unit-RF433
architectures=esp32
includes=M5UnitUnifiedRF433.h
depends=M5UnitUnified,M5Utility,M5HAL
